public enum DOC_TYPE
{
    INFO_OGRINAL = 10,
    INFO_PROTOBUF = 19,

    PDF_OGRINAL = 30,
    PDF_COMPRESS = 31,

    JPG_OGRINAL = 50,
    JPG_OGRINAL_SIZE = 51,
    JPG_NO_BORDER_PAGE = 60,
    JPG_LINES = 61,

    PNG_OGRINAL = 70,
    PNG_OGRINAL_SIZE = 71,
    PNG_NO_BORDER_PAGE = 78,
    PNG_LINES = 79,

    TEXT_OGRINAL = 80,
    TEXT_COMPRESS = 81,

    HTML_OGRINAL = 90,
    HTML_COMPRESS = 91,
}